# Generated by Django 5.2 on 2025-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(max_length=100)),
                ('city', models.CharField(default='Москва', max_length=50)),
                ('zodiac', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
